#!/bin/sh

set -e

# Only act on loopback interface actions
[ "$IFACE" = "lo" ] || exit 0

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

. /etc/default/wikimedia-lvs-realserver

# Compile a list of LVS service IPs currently bound to lo
LVS_SERVICE_IPS=$(ip addr show label "lo:LVS" | awk '{ print $2 }')

# Delete the service IPs from the loopback interface
for SIP in $LVS_SERVICE_IPS
do
	ip addr del $SIP label "lo:LVS" dev lo
done

# Also delete the IPv6
ip -6 addr ls dev lo scope global | sed -nr 's/.*inet6 //p' | while read SIPv6; do
	ip -6 addr del $SIPv6 dev lo
done
