#!/bin/sh

set -e

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Only act on loopback interface actions
[ "$IFACE" = "lo" ] || exit 0

. /etc/default/wikimedia-lvs-realserver

[ -z "$SYSCTLFILE" ] && exit 0
[ -z "$LVS_SERVICE_IPS" ] && exit 0

# Set the sysctl variables to ignore ARP for the LVS service IPs
sysctl -p $SYSCTLFILE

# Compile a list of LVS service IPs currently bound to lo
CURRENT_IPS=$(ip addr show label "lo:LVS" | awk '{ print $2 }')

# Delete the current service IPs from the loopback interface
for SIP in $CURRENT_IPS
do
        ip addr del $SIP label "lo:LVS" dev lo
done

# We don't have a label, so delete every globally scoped IPv6 from lo
ip -6 addr ls dev lo scope global | sed -nr 's/.*inet6 //p' | while read SIPv6; do
	ip -6 addr del $SIPv6 dev lo
done

# Add the service IPs to the loopback interface
for SIP in $LVS_SERVICE_IPS; do
	if echo $SIP | grep -q ":"; then
		# label is ignored on IPv6
		ip addr add $SIP/128 scope global dev lo
	else
		ip addr add $SIP/32 label "lo:LVS" dev lo
	fi
done
